
project_id = "tevtajmaofvnffzcsiuu"

[functions.firecrawl-scraper]
verify_jwt = false

[functions.inbound-email-webhook]
verify_jwt = false

[functions.inventory-cleanup-edge]
verify_jwt = true

[functions.twilio-webhook]
verify_jwt = false
